        const airdrops = [
                        {
                id: 11,
                title: "MinionLab",
                type: "depin",
                description: " Learn about MinionLab and its decentralized network of autonomous AI agents.",
                launchDate: "January 24, 2025",
                publishDate: new Date(2025, 3, 12),
                status: "Confirmed", 
                image: "Imagen/minion_lab.png ",
                referenceImage: "Imagen/fondosminionlab.jpeg",
                webUrl: "https://ref.minionlab.io/?referralCode=pJycWBNf",
                docsUrl: "https://docs.minionlab.ai/introduction",
                xUrl: "https://x.com/MinionLabAI ",
                badges: ["Web","Docs","X"],
                info: "MinionLab is a decentralized network of autonomous AI agents—called “Minions”—that run on user devices to mine real-time data from the internet.",
                funds:"$ 2.00 M",
                link: "https://ref.minionlab.io/?referralCode=pJycWBNf",
                participationSteps: [
                    { step: "Create or log in to your Google account", icon: "fa-google" },
                    { step: "Complete registration", icon: "fa-user-plus" },
                    {step: "download the extension", icon: "fa-download" },
                    { step: "Follow social media accounts", icon: "fa-share-alt" }
                ]
 
            },
            {
                id: 10,
                title: "Open Ledger",
                type: "depin",
                description: " The OpenLedger Testnet is the foundational step in building the OpenLedger ecosystem.",
                launchDate: "December 16, 2024",
                publishDate: new Date(2025, 3, 12),
                status: "Confirmed", 
                image: "Imagen/open_ledger.png ",
                referenceImage: "Imagen/fondosopenledger.jpeg",
                webUrl: "https://testnet.openledger.xyz/?referral_code=bjwpa2njgm",
                docsUrl: "https://openledger.gitbook.io/openledger",
                xUrl: " ",
                badges: ["Web","Docs","X"],
                info: "",
                funds:"$ 8.00 M",
                link: "https://testnet.openledger.xyz/?referral_code=bjwpa2njgm",
                participationSteps: [
                    { step: "Create or log in to your Google account", icon: "fa-google" },
                    { step: "Complete registration", icon: "fa-user-plus" },
                    { step: "Follow social media accounts", icon: "fa-share-alt" }
                ]
 
            },
            {
                id: 1,
                title: "TEKO",
                type: "social",
                description: "TEKO is an optimized lending platform that maximizes yields",
                launchDate: "February 24, 2025",
                publishDate: new Date(2025, 3, 12),
                image: " Imagen/teko.png",
                badges: ["Web", "X",],
                info: "TEKO is an optimized lending platform that maximizes yields, boosts capital efficiency, and minimizes risk with unparalleled speed and precision.",
                funds: "$0",
                link: "https://teko.finance/waitlist?ref_id=2TXNJSNXH"
            },
                            {
                id: 2,
                title: "Gradient Network  ",
               
                description: "The Gradient Network project is similar to Grass, Nodepay and Dawn",
                launchDate: "11 SEP, 2024",
                image: "Imagen/gradient_network.png",
                type: "depin",
                badges: ["Web", "X"],
                info: "Complete the tasks to qualify for potential Gradient Network airdrops and rewards",
                funds: "$0",
                link: " https://app.gradient.network/signup?code=SCCMOG"
            },
                           {
                id: 3,
                title: "Sparkchain",
                type: "depin",
                status: "Potential", 
                description: "Spark is a network of millions of people who are earning rewards for sharing unused internet bandwidth with the Spark network.",
                launchDate: "December 25, 2024",
                image: "Imagen/spark_chain.png",
                badges: ["Web", " Investors", "X"],
                info: " ",
                funds: "$0",
                link: "https://sparkchain.ai/register/?r=46670663"
            },
             {
                id: 4,
                title: "LayerEdge",
                type: "depin",
                description: "LayerEdge is the first decentralized network that enhances the capabilities of Bitcoin Blockspace with ZK & BitVM, enabling every layer to be secured on Bitcoin.",
                launchDate: " January 22, 2025",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/layeredge.png",
                webUrl: "https://layeredge.io/",
                docsUrl: "https://docs.layeredge.io/",
                xUrl: "https://x.com/LayerEdge",
                badges: ["Docs","X"
                ],
                info: "",
                funds:"$ 0",
                code: "9VfoH6D0",
                link: "https://dashboard.layeredge.io/",
                
            },
                         {
                id: 5,
                title: "3DOS",
                type: "depin",
                description: "3DOS™ is a global, decentralized manufacturing network for everyone.",
                launchDate: "February 11, 2025",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/3dos.png",
                webUrl: "https://3dos.gitbook.io/why-3dos-matters",
                docsUrl: "https://3dos.gitbook.io/why-3dos-matters",
                xUrl: "https://x.com/3DOS",
                badges: ["Web","Docs","X"
                ],
                info: "",
                funds:"$ 0",
                link: "https://dashboard.3dos.io/register?ref_code=caf5d1",
                
            },
                                   {
                id: 6,
                title: "NAORIS",
                type: "depin",
                description: "Naoris Protocol is a self-validating cybersecurity enforcement protocol that restores cyber-trust across digital systems.",
                launchDate: "January 30, 2025",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/naoris_protocol.png",
                webUrl: " https://www.naorisprotocol.com/",
                docsUrl: "",
                xUrl: "https://x.com/naorisprotocol",
                badges: ["Web","Docs","X"],
                info: "",
                funds:"$ 11.5 M",
                code: "oaWdlGjNa3N08eit",

                link: "https://naorisprotocol.network/testnet/tasks",
                
            },
                                            {
                id: 7,
                title: "DePINed",
                type: "depin",
                description: "DePINed.org is a revolutionary platform in GPU rental and AI development with one mission.",
                launchDate: "January 11, 2025",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/de_pi_ned.png",
                webUrl: "https://www.depined.org/",
                docsUrl: "https://www.depined.org/",
                xUrl: "https://x.com/DePINed_org",
                badges: ["Web","Docs","X"],
                info: "",
                funds:"$ 750K",
                code: "DEzaRpu4POHWl0",

                link: "https://app.depined.org/onboarding",
                
            },
                                                        {
                id: 8,
                title: "MyGate Network",
                type: "depin",
                description: "MyGate Network transforms everyday devices—your computer, smartphone, tablet—into powerful Virtual Private Servers (VPS)",
                launchDate: "January 1, 2025",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/my_gate_network.png",
                webUrl: " https://app.mygate.network/login?code=5HLopj",
                docsUrl: "https://mygate-network.gitbook.io/mygate-network",
                xUrl: "https://x.com/mygatenetwork",
                badges: ["Web","Docs","X"],
                info: "",
                funds:"$ 750K",
                link: "https://app.mygate.network/login?code=5HLopj",
                
            },
                                                                    {
                id: 9,
                title: "Fireverse",
                type: "social",
                description: "Complete Missions",
                launchDate: "",
                status: "Confirmed", 
                publishDate: new Date(2025, 3, 12),
                image: "Imagen/fireverse.png",
                referenceImage: "Imagen/fireverse fondo.jpg", 
                webUrl: "https://web3.fireverseai.com/login/?invite=ZCVLUA&url=https://app.fireverseai.com/user?task=1",
                docsUrl: "https://web3.fireverseai.com/login/?invite=ZCVLUA&url=https://app.fireverseai.com/user?task=1",
                xUrl: " ",
                badges: ["Web","Docs","X"],
                info: "",
                funds:"$ 2.5M",
                link: "https://web3.fireverseai.com/login/?invite=ZCVLUA&url=https://app.fireverseai.com/user?task=1",
                participationSteps: [
                    { step: "Connect your wallet", icon: "fa-wallet" },
                    { step: "Complete registration", icon: "fa-user-plus" },
                    { step: "Follow social media accounts", icon: "fa-share-alt" }
                ]
                
            },